[epydoc] # Epydoc section marker (required by ConfigParser)

# Information about the project.
name: ChiantiPy
url: http://sourceforge.net/projects/chiantipy/

# The list of modules to document.  Modules can be named using
# dotted names, module filenames, or package directory names.
# This option may be repeated.
modules: /home/dere/python/chianti/trunk/chiantipy/chianti
#modules: /home/dere/python/chiantipy/chianti/core.py
#modules: /home/dere/python/chiantipy/chianti/constants.py
#modules: /home/dere/python/chianti/util.py
#modules: /home/dere/python/chianti/filters.py
#modules: /home/dere/python/chianti/gui_cl/gui.py
#modules: /home/dere/python/chianti/gui_qt/gui.py
#modules: /home/dere/python/chianti/gui_qt/ui.py
#modules: /home/dere/python/chianti/gui_wx/gui.py
#modules: /home/dere/python/chianti/gui_wx/ui.py

#exclude:  setup.py

# Write html output to the directory "apidocs"
output: html
target: /home/dere/python/chianti/epydoc/